//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corsair_Effects_Engine.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string KeyboardModel {
            get {
                return ((string)(this["KeyboardModel"]));
            }
            set {
                this["KeyboardModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string KeyboardLayout {
            get {
                return ((string)(this["KeyboardLayout"]));
            }
            set {
                this["KeyboardLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string MouseModel {
            get {
                return ((string)(this["MouseModel"]));
            }
            set {
                this["MouseModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6: Engine Rendering Output")]
        public string LogLevel {
            get {
                return ((string)(this["LogLevel"]));
            }
            set {
                this["LogLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Spectrograph")]
        public string ForegroundEffect {
            get {
                return ((string)(this["ForegroundEffect"]));
            }
            set {
                this["ForegroundEffect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rainbow")]
        public string BackgroundEffect {
            get {
                return ((string)(this["BackgroundEffect"]));
            }
            set {
                this["BackgroundEffect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string StaticProfileName {
            get {
                return ((string)(this["StaticProfileName"]));
            }
            set {
                this["StaticProfileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForegroundEffectEnabled {
            get {
                return ((bool)(this["ForegroundEffectEnabled"]));
            }
            set {
                this["ForegroundEffectEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BackgroundEffectEnabled {
            get {
                return ((bool)(this["BackgroundEffectEnabled"]));
            }
            set {
                this["BackgroundEffectEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StaticProfileEnabled {
            get {
                return ((bool)(this["StaticProfileEnabled"]));
            }
            set {
                this["StaticProfileEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string AudioOutputDevice {
            get {
                return ((string)(this["AudioOutputDevice"]));
            }
            set {
                this["AudioOutputDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Headphones (Realtek High Definition Audio)")]
        public string AudioInputDevice {
            get {
                return ((string)(this["AudioInputDevice"]));
            }
            set {
                this["AudioInputDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptMinimizeToTray {
            get {
                return ((bool)(this["OptMinimizeToTray"]));
            }
            set {
                this["OptMinimizeToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptMinimizeOnClose {
            get {
                return ((bool)(this["OptMinimizeOnClose"]));
            }
            set {
                this["OptMinimizeOnClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Opt16MColours {
            get {
                return ((bool)(this["Opt16MColours"]));
            }
            set {
                this["Opt16MColours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptStartEffectsOnLoad {
            get {
                return ((bool)(this["OptStartEffectsOnLoad"]));
            }
            set {
                this["OptStartEffectsOnLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptLiveKeyboardPreview {
            get {
                return ((bool)(this["OptLiveKeyboardPreview"]));
            }
            set {
                this["OptLiveKeyboardPreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptWarnIfCueRunning {
            get {
                return ((bool)(this["OptWarnIfCueRunning"]));
            }
            set {
                this["OptWarnIfCueRunning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptLaunchCueOnExit {
            get {
                return ((bool)(this["OptLaunchCueOnExit"]));
            }
            set {
                this["OptLaunchCueOnExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptRestoreLightingOnExit {
            get {
                return ((bool)(this["OptRestoreLightingOnExit"]));
            }
            set {
                this["OptRestoreLightingOnExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OptCuePath {
            get {
                return ((string)(this["OptCuePath"]));
            }
            set {
                this["OptCuePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptStartWithWindows {
            get {
                return ((bool)(this["OptStartWithWindows"]));
            }
            set {
                this["OptStartWithWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptAudioFromInput {
            get {
                return ((bool)(this["OptAudioFromInput"]));
            }
            set {
                this["OptAudioFromInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptAudioFromOutput {
            get {
                return ((bool)(this["OptAudioFromOutput"]));
            }
            set {
                this["OptAudioFromOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte KeyboardHID {
            get {
                return ((byte)(this["KeyboardHID"]));
            }
            set {
                this["KeyboardHID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte MouseHID {
            get {
                return ((byte)(this["MouseHID"]));
            }
            set {
                this["MouseHID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fade")]
        public string ForegroundRandomLightsStyle {
            get {
                return ((string)(this["ForegroundRandomLightsStyle"]));
            }
            set {
                this["ForegroundRandomLightsStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int OptFrameDelay {
            get {
                return ((int)(this["OptFrameDelay"]));
            }
            set {
                this["OptFrameDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Random Colour")]
        public string ForegroundRandomLightsStartType {
            get {
                return ((string)(this["ForegroundRandomLightsStartType"]));
            }
            set {
                this["ForegroundRandomLightsStartType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string ForegroundRandomLightsEndType {
            get {
                return ((string)(this["ForegroundRandomLightsEndType"]));
            }
            set {
                this["ForegroundRandomLightsEndType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string ForegroundRandomLightsColorStartLower {
            get {
                return ((string)(this["ForegroundRandomLightsColorStartLower"]));
            }
            set {
                this["ForegroundRandomLightsColorStartLower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string ForegroundRandomLightsColorStartUpper {
            get {
                return ((string)(this["ForegroundRandomLightsColorStartUpper"]));
            }
            set {
                this["ForegroundRandomLightsColorStartUpper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string ForegroundRandomLightsColorEndLower {
            get {
                return ((string)(this["ForegroundRandomLightsColorEndLower"]));
            }
            set {
                this["ForegroundRandomLightsColorEndLower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string ForegroundRandomLightsColorEndUpper {
            get {
                return ((string)(this["ForegroundRandomLightsColorEndUpper"]));
            }
            set {
                this["ForegroundRandomLightsColorEndUpper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ForegroundRandomLightsFadeSolidDuration {
            get {
                return ((int)(this["ForegroundRandomLightsFadeSolidDuration"]));
            }
            set {
                this["ForegroundRandomLightsFadeSolidDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int ForegroundRandomLightsFadeTotalDuration {
            get {
                return ((int)(this["ForegroundRandomLightsFadeTotalDuration"]));
            }
            set {
                this["ForegroundRandomLightsFadeTotalDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string ForegroundRandomLightsSwitchColorStart {
            get {
                return ((string)(this["ForegroundRandomLightsSwitchColorStart"]));
            }
            set {
                this["ForegroundRandomLightsSwitchColorStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string ForegroundRandomLightsSwitchColorEnd {
            get {
                return ((string)(this["ForegroundRandomLightsSwitchColorEnd"]));
            }
            set {
                this["ForegroundRandomLightsSwitchColorEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int ForegroundRandomLightsSwitchDuration {
            get {
                return ((int)(this["ForegroundRandomLightsSwitchDuration"]));
            }
            set {
                this["ForegroundRandomLightsSwitchDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte BackgroundBrightness {
            get {
                return ((byte)(this["BackgroundBrightness"]));
            }
            set {
                this["BackgroundBrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int BackgroundRepeatTime {
            get {
                return ((int)(this["BackgroundRepeatTime"]));
            }
            set {
                this["BackgroundRepeatTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptInvertM1 {
            get {
                return ((bool)(this["OptInvertM1"]));
            }
            set {
                this["OptInvertM1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public string BackgroundRainbowDirection {
            get {
                return ((string)(this["BackgroundRainbowDirection"]));
            }
            set {
                this["BackgroundRainbowDirection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Defined Colour")]
        public string ForegroundReactiveStartType {
            get {
                return ((string)(this["ForegroundReactiveStartType"]));
            }
            set {
                this["ForegroundReactiveStartType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string ForegroundReactiveEndType {
            get {
                return ((string)(this["ForegroundReactiveEndType"]));
            }
            set {
                this["ForegroundReactiveEndType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string ForegroundReactiveColorStartLower {
            get {
                return ((string)(this["ForegroundReactiveColorStartLower"]));
            }
            set {
                this["ForegroundReactiveColorStartLower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string ForegroundReactiveColorEndLower {
            get {
                return ((string)(this["ForegroundReactiveColorEndLower"]));
            }
            set {
                this["ForegroundReactiveColorEndLower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string ForegroundReactiveColorStartUpper {
            get {
                return ((string)(this["ForegroundReactiveColorStartUpper"]));
            }
            set {
                this["ForegroundReactiveColorStartUpper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string ForegroundReactiveColorEndUpper {
            get {
                return ((string)(this["ForegroundReactiveColorEndUpper"]));
            }
            set {
                this["ForegroundReactiveColorEndUpper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ForegroundReactiveFadeSolidDuration {
            get {
                return ((int)(this["ForegroundReactiveFadeSolidDuration"]));
            }
            set {
                this["ForegroundReactiveFadeSolidDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int ForegroundReactiveFadeTotalDuration {
            get {
                return ((int)(this["ForegroundReactiveFadeTotalDuration"]));
            }
            set {
                this["ForegroundReactiveFadeTotalDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int ForegroundReactiveSwitchSolidDuration {
            get {
                return ((int)(this["ForegroundReactiveSwitchSolidDuration"]));
            }
            set {
                this["ForegroundReactiveSwitchSolidDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string ForegroundReactiveSwitchColorStart {
            get {
                return ((string)(this["ForegroundReactiveSwitchColorStart"]));
            }
            set {
                this["ForegroundReactiveSwitchColorStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string ForegroundReactiveSwitchColorEnd {
            get {
                return ((string)(this["ForegroundReactiveSwitchColorEnd"]));
            }
            set {
                this["ForegroundReactiveSwitchColorEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fade")]
        public string ForegroundReactiveStyle {
            get {
                return ((string)(this["ForegroundReactiveStyle"]));
            }
            set {
                this["ForegroundReactiveStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0080")]
        public string OptAccentColor {
            get {
                return ((string)(this["OptAccentColor"]));
            }
            set {
                this["OptAccentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF00FF")]
        public string ForegroundHeatmapColorMost {
            get {
                return ((string)(this["ForegroundHeatmapColorMost"]));
            }
            set {
                this["ForegroundHeatmapColorMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00FF00")]
        public string ForegroundHeatmapColorLeast {
            get {
                return ((string)(this["ForegroundHeatmapColorLeast"]));
            }
            set {
                this["ForegroundHeatmapColorLeast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public string BackgroundSolidColor {
            get {
                return ((string)(this["BackgroundSolidColor"]));
            }
            set {
                this["BackgroundSolidColor"] = value;
            }
        }
    }
}
